name: Deploy Python App

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t nishantkatare/python-app:latest .
        docker push nishantkatare/python-app:latest


  approval:
    name: Manual Approval Before Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: production
    timeout-minutes: 2

    steps:
      - name: Waiting for approval
        run: echo "Approve to start deployment..."


  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: approval

    steps:
    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.EC2_KEY }}

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker stop python-app || true
          docker rm python-app || true
          docker rmi nishantkatare/python-app:latest || true
          docker pull nishantkatare/python-app:latest
          docker run -d -p 8000:8000 --restart always --name python-app nishantkatare/python-app:latest
        EOF
