name: Deploy Python App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push (replace image)
      run: |
        docker build -t nishantkatare/python-app:latest .
        docker push nishantkatare/python-app:latest

    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.EC2_KEY }}

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker ps
          docker stop python-app || true
          docker rm python-app || true
          docker pull nishantkatare/python-app:latest
          docker run -d -p 8000:8000 --restart always --name python-app nishantkatare/python-app:latest
        EOF

#- --- IGNORE ---